# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'quickChat' do
pod 'IDMPhotoBrowser'
pod 'Backendless-ios-SDK'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'JSQMessagesViewController'
end

target 'quickChatTests' do

end

target 'quickChatUITests' do

end

