source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!

target 'faeBeta' do
    pod 'Alamofire’
    pod 'SwiftyJSON’
    pod 'JSQMessagesViewController'
    pod 'RealmSwift'
    pod 'TTRangeSlider'
    pod 'Gifu'
    pod 'IVBezierPathRenderer'
    pod 'GooglePlaces'
    pod 'CHIPageControl/Aleppo'
    pod 'CHIPageControl/Chimayo'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = ‘3.2’
    end
  end
  puts("Update debug pod settings to speed up build time")
  Dir.glob(File.join("Pods", "**", "Pods*{debug,Private}.xcconfig")).each do |file|
  File.open(file, 'a') { |f| f.puts "\nDEBUG_INFORMATION_FORMAT = dwarf" }
  end
end
