source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!

target 'faeBeta' do
	pod 'Alamofire’, '~> 4.1’
    pod 'SwiftyJSON'
	pod 'SDWebImage', '~>3.8’
	pod 'Firebase/Storage'
	pod 'Firebase/AdMob'
	pod 'Firebase/Auth'
	pod 'Firebase/Crash'
	pod 'Firebase/Database'
	pod 'Firebase/RemoteConfig'
	pod 'JSQMessagesViewController'
	pod 'IDMPhotoBrowser'
	pod 'KTCenterFlowLayout'
	pod 'GooglePlaces'
	pod 'GoogleMaps'
	pod 'RealmSwift'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end