source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!

target 'faeBeta' do
	pod 'Alamofire’, '~> 4.0'
    pod 'SwiftyJSON'
	pod 'SDWebImage', '~>3.8’
	pod 'Firebase/Storage'
	pod 'Firebase/AdMob'
	pod 'Firebase/Auth'
	pod 'Firebase/Crash'
	pod 'Firebase/Database'
	pod 'Firebase/RemoteConfig'
	pod 'JSQMessagesViewController'
	pod 'IDMPhotoBrowser'
	pod 'Backendless-ios-SDK'
	pod 'KTCenterFlowLayout'
	pod 'GooglePlaces'
	pod 'GoogleMaps'
end
